services:
  postgres_desafio2:
    image: postgres:15-alpine
    container_name: desafio2-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafio2
    volumes:
      - volume_desafio2_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - net-desafio2

  inspector_desafio2:
    image: postgres:15-alpine
    container_name: desafio2-inspector
    depends_on:
      - postgres_desafio2
    volumes:
      - volume_desafio2_data:/var/lib/postgresql/data
    networks:
      - net-desafio2
    entrypoint: ["sh", "-c", "tail -f /dev/null"]


networks:
  net-desafio2:
    driver: bridge

volumes:
  volume_desafio2_data:
